const getState = ({ getStore, getActions, setStore }) => {
  return {
    store: {
      message: null,
      user: [],
      regiones: [
        {
          NombreRegion: "Arica y Parinacota",
          comunas: ["Arica", "Camarones", "Putre", "General Lagos"],
        },
        {
          NombreRegion: "Tarapacá",
          comunas: [
            "Iquique",
            "Alto Hospicio",
            "Pozo Almonte",
            "Camiña",
            "Colchane",
            "Huara",
            "Pica",
          ],
        },
        {
          NombreRegion: "Antofagasta",
          comunas: [
            "Antofagasta",
            "Mejillones",
            "Sierra Gorda",
            "Taltal",
            "Calama",
            "Ollagüe",
            "San Pedro de Atacama",
            "Tocopilla",
            "María Elena",
          ],
        },
        {
          NombreRegion: "Atacama",
          comunas: [
            "Copiapó",
            "Caldera",
            "Tierra Amarilla",
            "Chañaral",
            "Diego de Almagro",
            "Vallenar",
            "Alto del Carmen",
            "Freirina",
            "Huasco",
          ],
        },
        {
          NombreRegion: "Coquimbo",
          comunas: [
            "La Serena",
            "Coquimbo",
            "Andacollo",
            "La Higuera",
            "Paiguano",
            "Vicuña",
            "Illapel",
            "Canela",
            "Los Vilos",
            "Salamanca",
            "Ovalle",
            "Combarbalá",
            "Monte Patria",
            "Punitaqui",
            "Río Hurtado",
          ],
        },
        {
          NombreRegion: "Valparaíso",
          comunas: [
            "Valparaíso",
            "Casablanca",
            "Concón",
            "Juan Fernández",
            "Puchuncaví",
            "Quintero",
            "Viña del Mar",
            "Isla de Pascua",
            "Los Andes",
            "Calle Larga",
            "Rinconada",
            "San Esteban",
            "La Ligua",
            "Cabildo",
            "Papudo",
            "Petorca",
            "Zapallar",
            "Quillota",
            "Calera",
            "Hijuelas",
            "La Cruz",
            "Nogales",
            "San Antonio",
            "Algarrobo",
            "Cartagena",
            "El Quisco",
            "El Tabo",
            "Santo Domingo",
            "San Felipe",
            "Catemu",
            "Llaillay",
            "Panquehue",
            "Putaendo",
            "Santa María",
            "Quilpué",
            "Limache",
            "Olmué",
            "Villa Alemana",
          ],
        },
        {
          NombreRegion: "Región del Libertador Gral. Bernardo O’Higgins",
          comunas: [
            "Rancagua",
            "Codegua",
            "Coinco",
            "Coltauco",
            "Doñihue",
            "Graneros",
            "Las Cabras",
            "Machalí",
            "Malloa",
            "Mostazal",
            "Olivar",
            "Peumo",
            "Pichidegua",
            "Quinta de Tilcoco",
            "Rengo",
            "Requínoa",
            "San Vicente",
            "Pichilemu",
            "La Estrella",
            "Litueche",
            "Marchihue",
            "Navidad",
            "Paredones",
            "San Fernando",
            "Chépica",
            "Chimbarongo",
            "Lolol",
            "Nancagua",
            "Palmilla",
            "Peralillo",
            "Placilla",
            "Pumanque",
            "Santa Cruz",
          ],
        },
        {
          NombreRegion: "Región del Maule",
          comunas: [
            "Talca",
            "ConsVtución",
            "Curepto",
            "Empedrado",
            "Maule",
            "Pelarco",
            "Pencahue",
            "Río Claro",
            "San Clemente",
            "San Rafael",
            "Cauquenes",
            "Chanco",
            "Pelluhue",
            "Curicó",
            "Hualañé",
            "Licantén",
            "Molina",
            "Rauco",
            "Romeral",
            "Sagrada Familia",
            "Teno",
            "Vichuquén",
            "Linares",
            "Colbún",
            "Longaví",
            "Parral",
            "ReVro",
            "San Javier",
            "Villa Alegre",
            "Yerbas Buenas",
          ],
        },
        {
          NombreRegion: "Región del Biobío",
          comunas: [
            "Concepción",
            "Coronel",
            "Chiguayante",
            "Florida",
            "Hualqui",
            "Lota",
            "Penco",
            "San Pedro de la Paz",
            "Santa Juana",
            "Talcahuano",
            "Tomé",
            "Hualpén",
            "Lebu",
            "Arauco",
            "Cañete",
            "Contulmo",
            "Curanilahue",
            "Los Álamos",
            "Tirúa",
            "Los Ángeles",
            "Antuco",
            "Cabrero",
            "Laja",
            "Mulchén",
            "Nacimiento",
            "Negrete",
            "Quilaco",
            "Quilleco",
            "San Rosendo",
            "Santa Bárbara",
            "Tucapel",
            "Yumbel",
            "Alto Biobío",
            "Chillán",
            "Bulnes",
            "Cobquecura",
            "Coelemu",
            "Coihueco",
            "Chillán Viejo",
            "El Carmen",
            "Ninhue",
            "Ñiquén",
            "Pemuco",
            "Pinto",
            "Portezuelo",
            "Quillón",
            "Quirihue",
            "Ránquil",
            "San Carlos",
            "San Fabián",
            "San Ignacio",
            "San Nicolás",
            "Treguaco",
            "Yungay",
          ],
        },
        {
          NombreRegion: "Región de la Araucanía",
          comunas: [
            "Temuco",
            "Carahue",
            "Cunco",
            "Curarrehue",
            "Freire",
            "Galvarino",
            "Gorbea",
            "Lautaro",
            "Loncoche",
            "Melipeuco",
            "Nueva Imperial",
            "Padre las Casas",
            "Perquenco",
            "Pitrufquén",
            "Pucón",
            "Saavedra",
            "Teodoro Schmidt",
            "Toltén",
            "Vilcún",
            "Villarrica",
            "Cholchol",
            "Angol",
            "Collipulli",
            "Curacautín",
            "Ercilla",
            "Lonquimay",
            "Los Sauces",
            "Lumaco",
            "Purén",
            "Renaico",
            "Traiguén",
            "Victoria",
          ],
        },
        {
          NombreRegion: "Región de Los Ríos",
          comunas: [
            "Valdivia",
            "Corral",
            "Lanco",
            "Los Lagos",
            "Máfil",
            "Mariquina",
            "Paillaco",
            "Panguipulli",
            "La Unión",
            "Futrono",
            "Lago Ranco",
            "Río Bueno",
          ],
        },
        {
          NombreRegion: "Región de Los Lagos",
          comunas: [
            "Puerto Montt",
            "Calbuco",
            "Cochamó",
            "Fresia",
            "FruVllar",
            "Los Muermos",
            "Llanquihue",
            "Maullín",
            "Puerto Varas",
            "Castro",
            "Ancud",
            "Chonchi",
            "Curaco de Vélez",
            "Dalcahue",
            "Puqueldón",
            "Queilén",
            "Quellón",
            "Quemchi",
            "Quinchao",
            "Osorno",
            "Puerto Octay",
            "Purranque",
            "Puyehue",
            "Río Negro",
            "San Juan de la Costa",
            "San Pablo",
            "Chaitén",
            "Futaleufú",
            "Hualaihué",
            "Palena",
          ],
        },
        {
          NombreRegion: "Región Aisén del Gral. Carlos Ibáñez del Campo",
          comunas: [
            "Coihaique",
            "Lago Verde",
            "Aisén",
            "Cisnes",
            "Guaitecas",
            "Cochrane",
            "O’Higgins",
            "Tortel",
            "Chile Chico",
            "Río Ibáñez",
          ],
        },
        {
          NombreRegion: "Región de Magallanes y de la AntárVca Chilena",
          comunas: [
            "Punta Arenas",
            "Laguna Blanca",
            "Río Verde",
            "San Gregorio",
            "Cabo de Hornos (Ex Navarino)",
            "AntárVca",
            "Porvenir",
            "Primavera",
            "Timaukel",
            "Natales",
            "Torres del Paine",
          ],
        },
        {
          NombreRegion: "Región Metropolitana de Santiago",
          comunas: [
            "Cerrillos",
            "Cerro Navia",
            "Conchalí",
            "El Bosque",
            "Estación Central",
            "Huechuraba",
            "Independencia",
            "La Cisterna",
            "La Florida",
            "La Granja",
            "La Pintana",
            "La Reina",
            "Las Condes",
            "Lo Barnechea",
            "Lo Espejo",
            "Lo Prado",
            "Macul",
            "Maipú",
            "Ñuñoa",
            "Pedro Aguirre Cerda",
            "Peñalolén",
            "Providencia",
            "Pudahuel",
            "Quilicura",
            "Quinta Normal",
            "Recoleta",
            "Renca",
            "San Joaquín",
            "San Miguel",
            "San Ramón",
            "Vitacura",
            "Puente Alto",
            "Pirque",
            "San José de Maipo",
            "Colina",
            "Lampa",
            "Tiltil",
            "San Bernardo",
            "Buin",
            "Calera de Tango",
            "Paine",
            "Melipilla",
            "Alhué",
            "Curacaví",
            "María Pinto",
            "San Pedro",
            "Talagante",
            "El Monte",
            "Isla de Maipo",
            "Padre Hurtado",
            "Peñaflor",
          ],
        },
      ],
      demo: [
        {
          title: "FIRST",
          background: "white",
          initial: "white",
        },
        {
          title: "SECOND",
          background: "white",
          initial: "white",
        },
      ],
      doctor: [
        {
          namefirst: "Marlon",
          namelast: "Mini",
          email: "maidservantsSusanne@catkinsphiltersdisplays.gov",
          age: "36",
          money: "$24168.9",
          city: "Louisville",
        },
        {
          namefirst: "Zachary",
          namelast: "Kaeser",
          email: "townBurgessSpielbergs@rarityssurfaces.gov",
          age: "35",
          money: "$58864.43",
          city: "Gainesville",
        },
        {
          namefirst: "Jerry",
          namelast: "Kickliter",
          email: "afflictionBelgiums@ripostedmisconstrued.com",
          age: "87",
          money: "$62066.98",
          city: "Abilene",
        },
        {
          namefirst: "Lawerence",
          namelast: "Lloret",
          email: "squandergrieved@papergirlsabjuring.com",
          age: "86",
          money: "$91957.87",
          city: "Corpus Christi",
        },
        {
          namefirst: "Marquis",
          namelast: "Laurenti",
          email: "Newarksoliderstultifies@amortized.net",
          age: "50",
          money: "$50295.52",
          city: "Oxnard",
        },
        {
          namefirst: "Keven",
          namelast: "Lisby",
          email: "phalanxmouthpiece@smithiespottierthermal.edu",
          age: "11",
          money: "$89178.9",
          city: "Antioch",
        },
        {
          namefirst: "Mauricio",
          namelast: "Margulies",
          email: "oleanderssandblasted@betokenedawkwarder.edu",
          age: "51",
          money: "$18866.25",
          city: "Tucson",
        },
        {
          namefirst: "Jules",
          namelast: "Koscher",
          email: "crusadeintroducingflagstaffs@platoons.com",
          age: "13",
          money: "$69676.61",
          city: "Stamford",
        },
        {
          namefirst: "Brandon",
          namelast: "Lipsey",
          email: "believingentered@hydrogenates.me",
          age: "91",
          money: "$54116.41",
          city: "Phoenix",
        },
        {
          namefirst: "Corey",
          namelast: "Conesa",
          email: "despairedMondrian@godlessOkinawas.edu",
          age: "56",
          money: "$63244.84",
          city: "Gresham",
        },
      ],
    },
    actions: {
      // Use getActions to call a function within a fuction
      exampleFunction: () => {
        getActions().changeColor(0, "green");
      },
      saveUser: (data) => {
        setStore({ user: data });
      },
      getMessage: () => {
        // fetching data from the backend
        fetch(process.env.BACKEND_URL + "/api/hello")
          .then((resp) => resp.json())
          .then((data) => setStore({ message: data.message }))
          .catch((error) =>
            console.log("Error loading message from backend", error)
          );
      },
      changeColor: (index, color) => {
        //get the store
        const store = getStore();

        //we have to loop the entire demo array to look for the respective index
        //and change its color
        const demo = store.demo.map((elm, i) => {
          if (i === index) elm.background = color;
          return elm;
        });

        //reset the global store
        setStore({ demo: demo });
      },
    },
  };
};

export default getState;
