"""empty message

Revision ID: 27b35479742d
Revises: 934099dfa8e2
Create Date: 2022-05-24 05:24:20.646560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b35479742d'
down_revision = '934099dfa8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialist', sa.Column('specialist_field', sa.Enum('veterinario', 'dentista', 'kinesiologo', 'psicologo', 'psiquiatra', 'nutricionista', name='specialistfield'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialist', 'specialist_field')
    # ### end Alembic commands ###
