"""empty message

Revision ID: d190ca8013ed
Revises: 13dd3914e8d9
Create Date: 2022-05-12 12:56:42.478151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd190ca8013ed'
down_revision = '13dd3914e8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialist',
    sa.Column('specialist_id', sa.Integer(), nullable=False),
    sa.Column('specialist_name', sa.String(length=120), nullable=True),
    sa.Column('specialist_lastname', sa.String(length=120), nullable=True),
    sa.Column('special_field', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('descrpition', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('specialist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialist')
    # ### end Alembic commands ###
